language: node_js

services: docker

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - sh scripts/create-config.sh

script:
  - docker-compose build && docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
