language: node_js

services: docker

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - echo '{"jwtSecret": "defaultsecret", "jwtExpiry": 300, "mongoURI": "mongodb://mongo:27017/taxe-server"}' >> config.json

script:
  - npm test
