version: "3"
services:
  app-test:
    container_name: app-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
