version: "3"
services:
  taxe:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
