# Get official base image for node.js and npm
FROM node:latest

# Copy Application files
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app

# TODO: Environment variables
ENV NODE_ENV prod

# Download required packages
RUN npm install
COPY . /usr/src/app

# Expose ports
EXPOSE 3000

# Run node.js
CMD node ./bin/www
