version: "3"
services:
  app:
    container_name: app
    restart: always
    image: taxe/app
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./bin/data/prod:/data/db
